fixtures:
  # Fixtures should also be added to <module>/spec/spec_helper_acceptance.rb
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    concat: "puppetlabs/concat"
    apache: "puppetlabs/apache"
    postgresql: "puppetlabs/postgresql"
  symlinks:
    reviewboard: "#{source_dir}"
